# 플러그인 버전
버전: "1.0.0"

방해권 상인:
  가격: 100
  이름: "방해권 상인"
  제목: "&e방해권 상인"
  배경: true  # true: 배경 유리판 표시, false: 배경 없음

# 방해권 효과 확률 설정 (총합 100)
방해권:
  확률:
    blindness: 40
    jail: 30
    lightning: 20
    fish: 10
  이름: "&l&5랜덤 방해권"
  설명: "

    &e사람을 바라보고 우클릭하면 해당 플레이어에게 랜덤한 방해가 작동되는 방해권
    &e사람을 겨냥하지않고 우클릭하면 사용자 본인에게 작동하니 주의가 필요하다

    "
  효과시간:
    # 시간 포맷:
    # - 숫자만 입력: 초 단위 (예: "60")
    # - 초 단위: "30s" 또는 "30초"
    # - 분 단위: "5m" 또는 "5분"
    # - 시간 단위: "1h" 또는 "1시간"
    blindness: "1m"  # 1분

# 복어 상점 설정
복어 상점:
  가격: 100
  이름: "복어 상점"
  제목: "&e복어 상점"
  배경: false
  아이템:
    이름: "&e복어"
    설명: "&b구매가: %price%원"

